class Init
  attr_accessor temperature_value: Float
  attr_accessor scale_from: String
  attr_accessor scale_to: String
  attr_reader f_exit: String

  def initialize: -> (String | NilClass)
  def main_menu: -> (String | NilClass)
  def exit?: (String? value) -> boolish
  def convert: -> String
  def take_temperature: -> String
  def take_scale_from: -> String
  def take_scale_to: -> String
end
